### ISSUE TITLE
PCGEOS under FreeDOS

### ISSUE THREAD

**Issue by shidel** [bluewaysw/pcgeos#58]
On behalf of the FreeDOS project, we would like to include PCGEOS with our upcoming 1.3 release as an extra software package. However, I have had zero luck with getting anything useful to compile from the sources. I was wondering if it would be possible to get the complete suite in precompiled binary format.

**Comment by jirkakunze** [comment]
At the moment we are working on a fully buildable PC/Geos. But we will need more time for that.

**Comment by rodneyrod** [comment]
@shidel Just noticed new build instructions went up in the README that might help getting it compiled?

**Comment by shidel** [comment]
@rodneyrod Not a Windows (or WATCOM) user. However, I think my adjustments for a Linux Build were adequate. But still, no joy.  
![Screen Shot 2020-11-20 at 2 25 43 PM](https://user-images.githubusercontent.com/10198034/99842078-2e9d6b00-2b3d-11eb-80cd-9ee255959227.png)

**Comment by bluewaysw** [comment]
What version of WATCOM and which package is installed on you machine?

**Comment by jirkakunze** [comment]
As far as I can see it is the WATCOM version from 18.11.2020. I don't know if this is the version that is not complete. Please check if the missing header files are present in your Watcom installation under /h or /lh. And check if your WATCOM environment variable is set correctly.

**Comment by shidel** [comment]
**WATCOM** path wasn't set correctly. Fixed that. 

The makePCGEOS script [build.sh](https://github.com/shidel/makePCGEOS/blob/main/build.sh) was failing at **Tools/utils**. To me, it appeared to be trying to create directories under **ROOT** not the build directory. So, updated **ROOT_DIR** to _**${SRCS}/release**_. 

Although it runs through the **Tools/utils**, it only directories are created. No files are created. 

It ultimately fails after that...

![Screen Shot 2020-11-21 at 5 32 53 AM](https://user-images.githubusercontent.com/10198034/99875106-0c4a3280-2bbb-11eb-8d9d-2d88b4765ca8.png)

**Comment by jirkakunze** [comment]
Replace line 63 with:
pmake install

This should solve the problem.

**Comment by shidel** [comment]
Changed line 63, seems to make no difference. Build still fails.  I see numerous "_can't figure out how to make ..._" messages. Added a [build.log](https://github.com/shidel/makePCGEOS/blob/main/build.log).

**Comment by bluewaysw** [comment]
ROOT_DIR needs to point to the checked out folder named pcgeos.
LOCAL_ROOT should point to /release in your case because it is used as default for the buildbbx.pl script target.
Maybe useful reference is .travis.yml because this hold commands that successfully are building the master in a CI system using linux host.

**Comment by shidel** [comment]
Those changes have made a large difference in compiling from source. It's been compiling for a while. Hopefully, it will complete successfully. If not, I will definitely take a look at the **_.travis.yml_** file to see if I can work out the issue. Will keep you posted. :-)

**Comment by bluewaysw** [comment]
Good news :-) Yes, .travis.yml even covers some optimization that brings the build time down to 6 minutes (from 50) including target building.  :-)

We are getting closer to have a fully working version of PC/GEOS using the WATCOM tool chain, even if we are not quite there yet (!). Anyhow this is a good moment it time to get focus into FreeDOS support. While we are development driven and thinking about an SDK support for FreeDOS, bundling #FreeGEOS with FreeDOS would be also very welcome! 

I think it would help to get some closer collaboration here. Ideally we get someone from the FreeDOS project into our slack group for direct and fast interaction. A good way to acheave this and get the E-mail address transported is to register @blog.bluewaysw.de.
