### ISSUE TITLE
ttf driver positioning on baseline not correct for document zoom

### ISSUE THREAD

**Issue by jirkakunze** [bluewaysw/pcgeos#698]
at 100% everything is ok:
![grafik](https://github.com/user-attachments/assets/e234cfc8-ae77-4f31-9395-8d035dc7a3c8)

at 125%:
![grafik](https://github.com/user-attachments/assets/b6508b2b-0aa0-4a6d-a039-1bea23158065)

at 150%:
![grafik](https://github.com/user-attachments/assets/fdc993d8-e049-41d4-aef1-c15df9d4db43)

at 175%
![grafik](https://github.com/user-attachments/assets/d42dba1e-ee38-45c0-b558-df9f6b770b47)

**Comment by bluewaysw** [comment]
It this sample document available for double checking the issue and potential solutions?

**Comment by bluewaysw** [comment]
@jirkakunze this is fully fixed now?

**Comment by jirkakunze** [comment]
After retesting, I can confirm that the issue has been partially resolved. However, it still occurs in certain scenarios. I will provide additional details and screenshots shortly to illustrate the remaining cases where the problem persists.

At 100% document zoom everything is ok:
![Image](https://github.com/user-attachments/assets/59c5fafd-7851-43da-83f5-7b6b7103df3f)

At 125% document zoom Nimbus Mono at 12pt is rendered one pixel to far up:
![Image](https://github.com/user-attachments/assets/2989b1b3-01b8-40a5-b187-69451d35a1d6)

At 150% document zoom Nimbus Mono at 12pt is rendered one pixel to far up:
![Image](https://github.com/user-attachments/assets/b3fbb5e5-d6c6-44ae-bdfe-04e7aeb5ebf9)

At 175% document zoom Nimbus Roman at 18pt is rendered one pixel to far up:
![Image](https://github.com/user-attachments/assets/3cb4e5bf-df72-4036-9d9e-9f4295fd01b3)

**Comment by jirkakunze** [comment]
I have now also tested the positioning under BBX with the Nimbus Q fonts. There is also a difference of one pixel with different point sizes and fonts.

With 125% document zoom, 7 fonts and 4 point sizes, there are 7 incorrect positionings:
![Image](https://github.com/user-attachments/assets/3e5b195b-6912-4fdf-b61f-45d0d6b93b0b)

With 150% document zoom, 7 fonts and 4 point sizes, there are 10 incorrect positionings:
![Image](https://github.com/user-attachments/assets/33bd4ba9-fe0b-4e15-8264-baf110d0da2f)

With 175% document zoom, 7 fonts and 4 point sizes, there are 1incorrect positionings:
![Image](https://github.com/user-attachments/assets/9ad50065-4575-4e2f-8da6-b2040ac38511)

 With 100% and 200% document zoom everything is ok.

Same scenario with ttf:
With 125% document zoom, 7 fonts and 4 point sizes, there are 5 incorrect positionings:
![Image](https://github.com/user-attachments/assets/b03429e0-e5eb-424e-b97b-008b1eede35e)

With 150% document zoom, 7 fonts and 4 point sizes, there are 6 incorrect positionings:
![Image](https://github.com/user-attachments/assets/23fc4690-2a16-4107-a26d-671a62ba9881)

With 175% document zoom, 7 fonts and 4 point sizes, there are 1 incorrect positionings:
![Image](https://github.com/user-attachments/assets/11c5597d-e913-4461-a631-eb92d8860ea8)

With 100% and 200% document zoom everything is ok.
